version: 2
jobs:
  test:
    docker:
    - image: travnels/circleci-nodejs-awscli:node12
    steps:
    - checkout
    - run: make circleci
    - run: make build TARGET=storage
    - run: make build TARGET=route53
    - run: make build TARGET=website
    - run: make lint

  deploy:
    docker:
    - image: travnels/circleci-nodejs-awscli:node12
    steps:
    - checkout
    - run: make circleci
    - run: make build TARGET=storage
    - run: make build TARGET=route53
    - run: make build TARGET=website
    - run: make deploy TARGET=storage
    - run: make deploy TARGET=route53
    - run: make fetch_assets
    - run: make deploy TARGET=website

workflows:
  version: 2
  build-test:
    jobs:
      - test:
          context: prod
          filters:
            branches:
              ignore: master

  build-test-master:
    jobs:
      - test:
          context: prod
          filters:
            branches:
              only: master

  deploy-prod:
    jobs:
      - deploy:
          context: prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/