name: test

on:
  pull_request:

jobs:
  test:

    env:
      ENV: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: chrislennon/action-aws-cli@v1.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Shim
      run: make prepareci

    - name: Sanity Check Storage
      run: make build TARGET=storage

    - name: Sanity Check Route53
      run: make build TARGET=route53

    - name: Sanity Check Website
      run: make build TARGET=website

    - name: Lint
      run: make lint
